# Site Identity
title: "Buddhafield 2026 Solar Power Information Repository"
description: "Capturing energy generation and consumption data, along with photographs, inventory, etc."
url: "https://buddhafield-solar.github.io" # Your production domain without trailing slash
baseurl: "" # Leave empty for root user/org site, or "/repo-name" if hosted on a subpath

# Localization
lang: "en-GB"
timezone: "Europe/London"

# Build Settings
plugins:
  - jekyll-seo-tag

# Exclude generated / system folders from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/

collections:
  installations:
    output: true
    permalink: /installations/:name/